### ISSUE TITLE
Ad Templates Needed

### ISSUE THREAD

**Issue by cwiklata** [dig-eg-gaz/advertisements#12]
Peninsular and Oriental S. N. Company
         - mine doesn't fit close enough to the given templates

Thos. Cook and Sons
         - bottom half of template is completely different

Deutsche Levant-Linie
         - incorrect ad format

Reisebureau der Hamburg-Amerika Linie
        - Need a template

Thanks!

**Comment by whanley** [comment]
These four are now done--thanks!
