### ISSUE TITLE
Missing Ads

### ISSUE THREAD

**Issue by JBaenen** [dig-eg-gaz/advertisements#15]
Missing:
Insurance Ad
Law union &amp; Crown insurance company of London, England.
Anglo-American Nile Steamer &amp; Hotel Coy.
 MESSRS. HENRY J. MONSONS &amp; Co's
 new template Peninsular and Oriental
 new template for Eastern Telegraph Company, Limited. in French

for 1905-02-27

**Comment by whanley** [comment]
1. https://dig-eg-gaz.github.io/advertisements/#ela01-edinburgh-life-assurance-company
2. https://dig-eg-gaz.github.io/advertisements/#luc01-law-union--crown-insurance-co
3. https://dig-eg-gaz.github.io/advertisements/#aan04-anglo-american-nile-streamer--hotel-coy
4. https://dig-eg-gaz.github.io/advertisements/#hjm01-henry-j-monson
5. https://dig-eg-gaz.github.io/advertisements/#pos04-peninsular-and-oriental-sn-company
6. https://dig-eg-gaz.github.io/advertisements/#etc02-the-eastern-telegraph-company-limited
