### ISSUE TITLE
Henderson&Co's Line

### ISSUE THREAD

**Issue by AlexisFitz** [dig-eg-gaz/advertisements#18]
I couldn't find a template for this advertisement so this is what I came up with. 
<div type="advert" xml:id="deg-ad-phc01">
                    <head>P. HENDERSON &amp; CO’s LINE.</head>
                    <p>Steamers leave SUEZ and PORT SAID fortnightly for LONDON or LIVERPOOL
                        direct.</p>
                    <p><name>S.S. AVA</name>
                        <measure quantity="7800" unit="ton">7800</measure> Tons will leave PORT SAID
                        about <date when="1906-12-16">December 16</date> for London.</p>
                    <p><name>S.S. TENASSERIM</name>
                        <measure quantity="7300" unit="ton">7300</measure> Tons will leave PORT SAID
                        about <date when="1907-01-12">January 11</date> for Dover.</p>
                    <p><name>S.S. AMARAPOORA</name>
                        <measure quantity="6600" unit="ton">6600</measure>to follow</p>
                    <p>Due in LONDON or LIVERPOOL 12 days thereafter.</p>
                    <p>Apply WORMS &amp; Co., Port Said and Suez. THOS. COOK &amp; SON, (EGYPT) LD.,
                        CAIRO ;</p>
                    <p>G. J. GRACE &amp; CO., ALEXANDRIA.</p>
                </div>

**Comment by whanley** [comment]
This appears to be the same as https://dig-eg-gaz.github.io/advertisements/#phc01-p-henderson--cos-line. Only the names of ships and dates and destinations change. Please update these yourself. Let me know if this doesn't make sense.
