### ISSUE TITLE
Missing Advertisement: Russian Steam Navigation

### ISSUE THREAD

**Issue by Lionex** [dig-eg-gaz/advertisements#2]
Missing advertisement boilerplate from ad found in 7th Oct 1905 issue, page 1.

Advertisement for Russian Steam Navigation company.

Image attached here:

![rsn1](https://cloud.githubusercontent.com/assets/14112725/19747747/872f5bd2-9bab-11e6-8cb2-60df1b0df4f1.png)

**Comment by whanley** [comment]
Now posted as rsn1--though website is slow to update.

**Comment by whanley** [comment]
Here it is @Lionex https://dig-eg-gaz.github.io/advertisements/#rsn1-russian-steam-navigation
