### ISSUE TITLE
Missing Ad

### ISSUE THREAD

**Issue by patrickmason8** [dig-eg-gaz/advertisements#20]
Titled Summer Trips to Cyprus
![screen shot 2018-01-29 at 11 04 34 pm](https://user-images.githubusercontent.com/35532713/35628590-6280d470-066a-11e8-8cd8-7ea27d7890c0.png)

**Comment by whanley** [comment]
Now posted: https://dig-eg-gaz.github.io/advertisements/#bam03-summer-trips-to-cyprus
