### ISSUE TITLE
Missing templates for ads

### ISSUE THREAD

**Issue by wavyncurly** [dig-eg-gaz/advertisements#22]
<img width="199" alt="screen shot 2018-02-12 at 12 45 50 pm" src="https://user-images.githubusercontent.com/35303030/36111395-f80d5e54-0ff3-11e8-9052-83968c5f9917.png">

<img width="205" alt="screen shot 2018-02-12 at 12 46 02 pm" src="https://user-images.githubusercontent.com/35303030/36111396-f8230588-0ff3-11e8-8b3c-a15d9e602a9a.png">

I've inserted the screenshots above.

**Comment by whanley** [comment]
1st one is [here](https://dig-eg-gaz.github.io/advertisements/#hem01-hemagene-tailleur)
2nd one is [here](https://dig-eg-gaz.github.io/advertisements/#eec04-pulsometer--the-egyptian-engineering-co-ltd)
