### ISSUE TITLE
1907-02-06-p2 ads need templates

### ISSUE THREAD

**Issue by SophiaElizabeth** [dig-eg-gaz/advertisements#31]
![vaughn-jones ad](https://user-images.githubusercontent.com/35302983/37879705-e1305958-304a-11e8-8a43-427047bb5cc3.JPG)
![mclaren ad](https://user-images.githubusercontent.com/35302983/37879707-e4a25d7a-304a-11e8-8d17-7969345f2eaf.JPG)

**Comment by whanley** [comment]
images saved

**Comment by whanley** [comment]
done. msp02 & vjs01
