### ISSUE TITLE
Cleopatra Cigarette ad

### ISSUE THREAD

**Issue by SophiaElizabeth** [dig-eg-gaz/advertisements#35]
1907-02-07-p2
![cleopatra cigarettes](https://user-images.githubusercontent.com/35302983/37880086-1f2a438a-3051-11e8-93f1-53f91894e644.JPG)

**Comment by whanley** [comment]
image saved

**Comment by whanley** [comment]
This is already here: https://dig-eg-gaz.github.io/contents/advertisements/#ccc01-the-cleopatra-cigarette-co
