### ISSUE TITLE
need ads page 8 1907-02-08

### ISSUE THREAD

**Issue by SophiaElizabeth** [dig-eg-gaz/advertisements#39]
![corso](https://user-images.githubusercontent.com/35302983/38225480-1748531e-36c3-11e8-9b88-c89c2709d656.JPG)
![smokeless diamond](https://user-images.githubusercontent.com/35302983/38225483-1a754e98-36c3-11e8-92af-5369d2b97248.JPG)

**Comment by whanley** [comment]
downloaded images

**Comment by whanley** [comment]
done. sfc01 & sdc02
