### ISSUE TITLE
Missing Template; F. Reddaway & Co Limited Advertisement

### ISSUE THREAD

**Issue by 19peytonsmith** [dig-eg-gaz/advertisements#58]
I would write a template for this, but the advertisement is so dark and illegible I can't bother.

![Screenshot_13](https://user-images.githubusercontent.com/54728307/66185762-694cf700-e64e-11e9-824a-0a5eb5ddcfe9.jpg)

**Comment by whanley** [comment]
Yes that's tough. Maybe we'll find a clearer one...
